//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvImporter.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlStatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlStatements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsvImporter.DataAccess.SqlStatements", typeof(SqlStatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Created by Vladimir
        ///--Created 13/12/2020
        ///SELECT COUNT(*) FROM [StockProduct] WITH (NOLOCK).
        /// </summary>
        internal static string CountStock {
            get {
                return ResourceManager.GetString("CountStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Creator: Vladimir
        ///--Description: This sql create the stockproduct table
        ///IF OBJECT_ID(N&apos;StockProduct&apos;) IS NULL
        ///BEGIN
        ///CREATE TABLE [StockProduct](	
        ///	[PointOfSale] [nvarchar](200) NULL,
        ///	[Product] [nvarchar](200) NULL,
        ///	[Date] [datetime] NULL,
        ///	[Stock] [int] NULL)
        ///END
        ///.
        /// </summary>
        internal static string Create_StockProductTable {
            get {
                return ResourceManager.GetString("Create_StockProductTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Created by Vladimir
        ///--Created 12/12/2020
        ///DELETE FROM [StockProduct].
        /// </summary>
        internal static string DeleteMassStock {
            get {
                return ResourceManager.GetString("DeleteMassStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Created by Vladimir
        ///--Created 12/12/2020
        ///
        ///declare @sql nvarchar(MAX)
        ///declare @format varchar(10)
        ///--declare @path varchar(250)
        ///--set @path = &apos;D:\FileExcel\Stock.csv&apos;
        ///set @format=&apos;char&apos;
        ///
        ///set @sql= N&apos;BULK INSERT [StockProduct] 
        ///FROM &apos;&apos;&apos;+@path+&apos;&apos;&apos; WITH (DATAFILETYPE=&apos;&apos;&apos;+@format+&apos;&apos;&apos;,FIRSTROW = 2,
        ///    FIELDTERMINATOR = &apos;+&apos;&apos;&apos;;&apos;&apos;&apos;+&apos;,ROWTERMINATOR=&apos;+&apos;&apos;&apos;\n&apos;&apos;&apos;+&apos;);&apos;
        ///Execute sp_executesql @sql
        ///
        ///.
        /// </summary>
        internal static string SaveBulkData {
            get {
                return ResourceManager.GetString("SaveBulkData", resourceCulture);
            }
        }
    }
}
