//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvImporter.DataAccess {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlStatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlStatements() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsvImporter.DataAccess.SqlStatements", typeof(SqlStatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --Created by Vladimir
        ///--Created 13/12/2020
        ///SELECT COUNT(*) FROM [StockProduct] WITH (NOLOCK).
        /// </summary>
        internal static string CountStock {
            get {
                return ResourceManager.GetString("CountStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --Creator: Vladimir
        ///--Description: This sql create the stockproduct table
        ///IF OBJECT_ID(N&apos;StockProduct&apos;) IS NULL
        ///BEGIN
        ///CREATE TABLE [StockProduct](	
        ///	[PointOfSale] [nvarchar](200) NULL,
        ///	[Product] [nvarchar](200) NULL,
        ///	[Date] [datetime] NULL,
        ///	[Stock] [int] NULL)
        ///END
        ///.
        /// </summary>
        internal static string Create_StockProductTable {
            get {
                return ResourceManager.GetString("Create_StockProductTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --Created by Vladimir
        ///--Created 12/12/2020
        ///DELETE FROM [StockProduct].
        /// </summary>
        internal static string DeleteMassStock {
            get {
                return ResourceManager.GetString("DeleteMassStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --Created by Vladimir
        ///--Created 12/12/2020
        ///
        ///declare @sql nvarchar(MAX)
        ///declare @format varchar(10)
        ///--declare @path varchar(250)
        ///--set @path = &apos;D:\FileExcel\Stock.csv&apos;
        ///set @format=&apos;char&apos;
        ///
        ///set @sql= N&apos;BULK INSERT [StockProduct] 
        ///FROM &apos;&apos;&apos;+@path+&apos;&apos;&apos; WITH (DATAFILETYPE=&apos;&apos;&apos;+@format+&apos;&apos;&apos;,FIRSTROW = 2,
        ///    FIELDTERMINATOR = &apos;+&apos;&apos;&apos;;&apos;&apos;&apos;+&apos;,ROWTERMINATOR=&apos;+&apos;&apos;&apos;\n&apos;&apos;&apos;+&apos;);&apos;
        ///Execute sp_executesql @sql
        ///
        ///.
        /// </summary>
        internal static string SaveBulkData {
            get {
                return ResourceManager.GetString("SaveBulkData", resourceCulture);
            }
        }
    }
}
